const EVENT_TYPES = Object.freeze({
  PRICE_UPDATE: 'PRICE_UPDATE',
  NEWS_EVENT: 'NEWS_EVENT',
  VOLUME_SPIKE: 'VOLUME_SPIKE',
  GAP_DETECTED: 'GAP_DETECTED',
  STOCK_IN_PLAY: 'STOCK_IN_PLAY',
  SHORT_SQUEEZE: 'SHORT_SQUEEZE',
  FLOW_DETECTED: 'FLOW_DETECTED',
  DATA_INTEGRITY_WARNING: 'DATA_INTEGRITY_WARNING',
  PROVIDER_FAILURE: 'PROVIDER_FAILURE',
  ENGINE_FAILURE: 'ENGINE_FAILURE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  PRICE_ANOMALY: 'PRICE_ANOMALY',
  DUPLICATE_TICK: 'DUPLICATE_TICK',
  PROVIDER_DISCREPANCY: 'PROVIDER_DISCREPANCY',
});

module.exports = EVENT_TYPES;
