-- Phase F1: LLM narrative columns on beacon_v0_picks
-- Stores thesis + watch_for narrative generated by Claude Sonnet

ALTER TABLE beacon_v0_picks
  ADD COLUMN IF NOT EXISTS narrative_thesis TEXT,
  ADD COLUMN IF NOT EXISTS narrative_watch_for TEXT,
  ADD COLUMN IF NOT EXISTS narrative_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS narrative_model TEXT,
  ADD COLUMN IF NOT EXISTS narrative_input_tokens INTEGER,
  ADD COLUMN IF NOT EXISTS narrative_output_tokens INTEGER,
  ADD COLUMN IF NOT EXISTS narrative_error TEXT;

CREATE INDEX IF NOT EXISTS beacon_v0_picks_narrative_generated_idx
  ON beacon_v0_picks (narrative_generated_at);
