export const pageStatus = {
  InstitutionalScreener: { status: 'active', replacement: '/discovery/scanner' },
  ScreenerFull: { status: 'active', replacement: '/discovery/full-screener' },
  AdvancedScreenerPage: { status: 'active', replacement: '/discovery/advanced-screener' },
  OpenRangeRadar: { status: 'active', replacement: '/market/radar' },
  MarketOverviewPage: { status: 'active', replacement: '/market/overview' },
  SectorHeatmap: { status: 'active', replacement: '/market/sector-rotation' },
  NewsScannerV2: { status: 'active', replacement: '/market/news' },
  Charts: { status: 'active', replacement: '/trading/charts' },
  TradeSetup: { status: 'active', replacement: '/trading/setup' },
  LiveCockpit: { status: 'active', replacement: '/trading/cockpit' },
  IntelInbox: { status: 'active', replacement: '/beacon/hub' },
  IntelligenceEngine: { status: 'active', replacement: '/beacon/signals' },
  ScreenersPage: { status: 'compatibility', replacement: '/discovery/scanner' },
  NewsScannerPage: { status: 'compatibility', replacement: '/market/news' },
  ScreenerV2: { status: 'deprecated', replacement: '/discovery/scanner' },
  ScreenerV3: { status: 'deprecated', replacement: '/discovery/scanner' },
  NewsScannerV3: { status: 'deprecated', replacement: '/market/news' },
  ScannerSection: { status: 'deprecated', replacement: '/discovery/scanner' },
  OpenMarketPage: { status: 'deprecated', replacement: '/market/overview' },
  PreMarketPage: { status: 'deprecated', replacement: '/market/overview' },
  PostMarketPage: { status: 'deprecated', replacement: '/market/overview' },
  TickerHeatmap: { status: 'deprecated', replacement: '/market/sector-rotation' },
  ExpectedMovePage: { status: 'deprecated', replacement: '/discovery/expected-move' },
  PreMarketCommand: { status: 'deprecated', replacement: '/market/radar' },
  AdminPage: { status: 'deprecated', replacement: '/system/admin' },
  IntelligencePage: { status: 'deprecated', replacement: '/beacon/hub' },
};
